# selecciona libros
GET http://localhost:8080/api/libros
###

# selecciona libros
GET http://localhost:8080/api/libros/17
###

POST http://localhost:8080/api/libros
Content-Type: application/json

{
    "titulo": "Cien Años de Soledad",
    "isbn": "978-0307474478",
    "anoPublicacion": 1967,
    "genero": "NOVELA",
    "autor": {
        "id": 1
    }
}

###

POST http://localhost:8080/api/libros
Content-Type: application/json

{
    "titulo": "Lord of The Rings",
    "isbn": "978-0307474479",
    "anoPublicacion": 1954,
    "genero": "FANTASIA",
    "autor": {
        "id": 21
    }
}

###

POST http://localhost:8080/api/libros
Content-Type: application/json

{
    "titulo": "Mrs Dalloway",
    "isbn": "978-0156628709",
    "anoPublicacion": 1925,
    "genero": "NOVELA",
    "autor": {
        "id": 22
    }
}
###

